#! /usr/bin/env php
<?php

$possibleFiles = [
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/vendor/autoload.php'
];

foreach ($possibleFiles as $file) {
    if (file_exists($file)) {
        $theFile = $file;
        break;
    }
}

if (!isset($theFile)) {
    throw new Exception('You need to set up the project dependencies using Composer');
}

require $theFile;
unset($possibleFiles, $theFile);

if ($argc < 2) {
    echo "Please specify site you want to check!\n";
    exit(1);
}

$domains = $argv;
array_shift($domains);

foreach ($domains as $domain) {
    (new Alexsoft\Isup\Check)->check($domain);
}

exit(0);