#! /usr/bin/env php
<?php


if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

if ($argc < 2) {
    echo "Please specify site you want to check!\n";
    exit(1);
}

$domains = $argv;
array_shift($domains);

foreach ($domains as $domain) {
    (new Alexsoft\Isup\Check)->check($domain);
}

exit(0);